[package]
name = "cortex-m-linkme-test"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.5"
panic-semihosting = { version = "0.6", features = ["exit"] }

# cortex-m = "0.7"
# cortex-m-rt = "0.7"
# cortex-m-semihosting = "0.5"
# panic-semihosting = { version = "0.6", features = ["exit"] }

