name: CI

on:
  push

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cortex:
    name: Cortex-M
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: thumbv7m-none-eabi
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-arm
          rustc --version
          qemu-system-arm --version
          lsb_release -a
          free -m
      - run: |
          cargo build -p testsuite --target thumbv7m-none-eabi --features semihosting,cortex-m/critical-section-single-core
          qemu-system-arm \
            -cpu cortex-m3 \
            -machine lm3s6965evb \
            -nographic \
            -semihosting-config enable=on,target=native \
            -kernel target/thumbv7m-none-eabi/debug/testsuite
        working-directory: testsuite

  # hil-qemu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #         target: thumbv7m-none-eabi
  #     - name: Build testsuite
  #       env:
  #         RUSTFLAGS: -C link-arg=-Tlink.x -D warnings
  #       run: cd testsuite && cargo build -p testsuite --target thumbv7m-none-eabi --features semihosting,cortex-m/critical-section-single-core
  #     - name: Install QEMU
  #       run: sudo apt-get update && sudo apt-get install qemu qemu-system-arm
  #     - name: Run testsuite
  #       run: |
  #         qemu-system-arm \
  #           -cpu cortex-m3 \
  #           -machine lm3s6965evb \
  #           -nographic \
  #           -semihosting-config enable=on,target=native \
  #           -kernel testsuite/target/thumbv7m-none-eabi/debug/testsuite